# -*- coding: utf-8 -*-
"""MDM_LAB_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJN2Ug27oYyjo6KZf0YVtPYDaZfet0iA
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

data = {
    "Hours_Studied": [1,2,3,4,5,6,7,8,9,10],
    "Marks": [35,40,45,50,55,60,65,72,80,88]
}

df = pd.DataFrame(data)

X = df[["Hours_Studied"]]
y = df["Marks"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

print("\nActual vs Predicted")
for actual, predicted in zip(y_test, y_pred):
    print("Actual:", actual, "Predicted:", round(predicted, 2))

import numpy as np
import matplotlib.pyplot as plt

X = np.array([1,2,3,4,5,6,7,8,9,10], dtype=float)
y = np.array([35,40,45,50,55,60,65,72,80,88], dtype=float)

m = 0
b = 0
learning_rate = 0.01
epochs = 1000
n = len(X)

cost_history = []

for i in range(epochs):
    y_pred = m * X + b
    error = y_pred - y

    dm = (2/n) * np.sum(X * error)
    db = (2/n) * np.sum(error)

    m = m - learning_rate * dm
    b = b - learning_rate * db

    cost = np.mean(error ** 2)
    cost_history.append(cost)

print("Slope:", m)
print("Intercept:", b)
print("Final MSE:", cost_history[-1])

y_pred = m * X + b

plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("Hours Studied")
plt.ylabel("Marks")
plt.title("Linear Regression using Gradient Descent")
plt.show()

plt.plot(range(epochs), cost_history)
plt.xlabel("Epochs")
plt.ylabel("MSE")
plt.title("Gradient Descent Convergence")
plt.show()